name: Build/release

on: push

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  release:
    runs-on: ${{ matrix.os }}
    # runs-on: [self-hosted]

    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x]
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: List files in the repository
      run: |
          ls ${{ github.workspace }}

    - name: Test
    - run: go build -o keyvault-cli ./cli

    - name: List files in the repository
      run: |
          ls ${{ github.workspace }}


